apiVersion: v1

kind: Pod

metadata:

  name: dapi-envars-fieldref

spec:

  containers:

    - name: test-container

      image: registry.k8s.io/busybox

      command: [ "sh", "-c"]

      args:

      - while true; do

          echo -en '\n';

          printenv METADATA_UID METADATA_NAME METADATA_NAMESPACE;

          sleep 10;

        done;

      env:

        - name: METADATA_UID

          valueFrom:

            fieldRef:

              fieldPath: metadata.uid

        - name: METADATA_NAME

          valueFrom:

            fieldRef:

              fieldPath: metadata.name

        - name: METADATA_NAMESPACE

          valueFrom:

            fieldRef:

              fieldPath: metadata.namespace



  restartPolicy: Never

